// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Header.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "Header.h"

#include <microcdr/microcdr.h>
#include <string.h>

bool Header_serialize_topic(MicroBuffer* writer, const Header* topic)
{
    (void) Time_serialize_topic(writer, &topic->stamp);
    (void) serialize_sequence_char(writer, topic->frame_id, (uint32_t)strlen(topic->frame_id) + 1);
    return writer->error == BUFFER_OK;
}

bool Header_deserialize_topic(MicroBuffer* reader, Header* topic)
{
    uint32_t size_frame_id;
    (void) Time_deserialize_topic(reader, &topic->stamp);
    (void) deserialize_sequence_char(reader, topic->frame_id, &size_frame_id);
    return reader->error == BUFFER_OK;
}

uint32_t Header_size_of_topic(const Header* topic, uint32_t size)
{
    size  = Time_size_of_topic(&topic->stamp, size);
    size += 4 + get_alignment(size, 4) + (uint32_t)strlen(topic->frame_id) + 1;
    return size;
}