// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file LaserScan.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "LaserScan.h"

#include <microcdr/microcdr.h>
#include <string.h>

bool LaserScan_serialize_topic(MicroBuffer* writer, const LaserScan* topic)
{
    (void) Header_serialize_topic(writer, &topic->header);
    (void) serialize_float(writer, topic->angle_min);
    (void) serialize_float(writer, topic->angle_max);
    (void) serialize_float(writer, topic->angle_increment);
    (void) serialize_float(writer, topic->time_increment);
    (void) serialize_float(writer, topic->scan_time);
    (void) serialize_float(writer, topic->range_min);
    (void) serialize_float(writer, topic->range_max);
    (void) serialize_sequence_float(writer, topic->ranges, topic->ranges_size);(void) serialize_sequence_float(writer, topic->intensities, topic->intensities_size);
    return writer->error == BUFFER_OK;
}

bool LaserScan_deserialize_topic(MicroBuffer* reader, LaserScan* topic)
{
    (void) Header_deserialize_topic(reader, &topic->header);
    (void) deserialize_float(reader, &topic->angle_min);
    (void) deserialize_float(reader, &topic->angle_max);
    (void) deserialize_float(reader, &topic->angle_increment);
    (void) deserialize_float(reader, &topic->time_increment);
    (void) deserialize_float(reader, &topic->scan_time);
    (void) deserialize_float(reader, &topic->range_min);
    (void) deserialize_float(reader, &topic->range_max);
    (void) deserialize_sequence_float(reader, topic->ranges, &topic->ranges_size);(void) deserialize_sequence_float(reader, topic->intensities, &topic->intensities_size);
    return reader->error == BUFFER_OK;
}

uint32_t LaserScan_size_of_topic(const LaserScan* topic, uint32_t size)
{
    size  = Header_size_of_topic(&topic->header, size);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += (topic->ranges_size * 4) + get_alignment(size, 4);

    size += 4 + get_alignment(size, 4);
    size += (topic->intensities_size * 4) + get_alignment(size, 4);

    return size;
}
