// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Time.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "Time.h"

#include <microcdr/microcdr.h>
#include <string.h>

bool Time_serialize_topic(MicroBuffer* writer, const Time* topic)
{
    (void) serialize_int32_t(writer, topic->sec);
    (void) serialize_uint32_t(writer, topic->nanosec);

    return writer->error == BUFFER_OK;
}

bool Time_deserialize_topic(MicroBuffer* reader, Time* topic)
{
    (void) deserialize_int32_t(reader, &topic->sec);
    (void) deserialize_uint32_t(reader, &topic->nanosec);

    return reader->error == BUFFER_OK;
}

uint32_t Time_size_of_topic(const Time* topic, uint32_t size)
{
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);

    return size;
}