<?xml version="1.0" ?>
<robot name="turtlebot3_pizza" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find turtlebot3_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find turtlebot3_description)/urdf/turtlebot3_pizza.gazebo.xacro"/>

  <xacro:include filename="$(find sick_tim)/urdf/sick_tim.urdf.xacro" />
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />

  <xacro:arg name="use_nominal_extrinsics" default="false"/>
  <xacro:arg name="add_plug" default="false" />
  <xacro:arg name="use_mesh" default="true" />

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

  <xacro:property name="PI" value="3.14159265358979"/>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0.0 0.0 0.0365" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/bases/big_base.obj"/>
      </geometry>
      <!-- <material name="light_black"/> -->
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.4 0.02"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />
    </inertial>
  </link>


  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.09500003 0.232425 0.024" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/big_tire.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02425" radius="0.0605"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.170" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>


  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.09500003 -0.232425 0.024" rpy="${PI/2} 0 ${PI}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/big_tire.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02425" radius="0.0605"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.170" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>


  <joint name="dynx_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="dynx_left_link"/>
    <origin xyz="0.09500003 0.19 0.0" rpy="0 0 ${PI}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="dynx_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/dynamixel/XM540-W150-R.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <!-- <collision>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.044 0.03325003 0.07875"/>
      </geometry>
    </collision> -->
  </link>

  <joint name="dynx_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="dynx_right_link"/>
    <origin xyz="0.09500003 -0.19 0.0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="dynx_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/dynamixel/XM540-W150-R.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <!-- <collision>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.044 0.03325003 0.07875"/>
      </geometry>
    </collision> -->
  </link>


  <joint name="wheel_left_conn_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_left_conn_link"/>
    <origin xyz="0.09500003 0.19 0.0" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_conn_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/joints/big_tire_joint.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <!-- <collision>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.044 0.03325003 0.07875"/>
      </geometry>
    </collision> -->
  </link>


  <joint name="wheel_right_conn_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_right_conn_link"/>
    <origin xyz="0.09500003 -0.19 0.0" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_conn_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/joints/big_tire_joint.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <!-- <collision>
      <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.044 0.03325003 0.07875"/>
      </geometry>
    </collision> -->
  </link>


  <joint name="caster_back_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.13016029 0.23242569 -0.009" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="caster_back_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/big_caster.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <collision>
      <origin xyz="0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.015" radius="0.0275"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.170" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
      <!-- <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/> -->
    </inertial>
  </link>


  <joint name="caster_back_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.13016029 -0.23242569 -0.009" rpy="${PI/2} 0 ${PI}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="caster_back_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/big_caster.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <collision>
      <origin xyz="0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.015" radius="0.0275"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.170" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
      <!-- <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/> -->
    </inertial>
  </link>


  <joint name="caster_back_left_conn_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_conn_link"/>
    <origin xyz="-0.13016029 0.19 0.0" rpy="0 0 ${PI/2}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="caster_back_left_conn_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/joints/big_caster_joint.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <!-- <collision>
      <origin xyz="0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04192569 0.03325003 0.02952809"/>
      </geometry>
    </collision> -->
  </link>


  <joint name="caster_back_right_conn_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_conn_link"/>
    <origin xyz="-0.13016029 -0.19 0.0" rpy="0 0 ${-PI/2}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="caster_back_right_conn_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/joints/big_caster_joint.dae"/>
      </geometry>
      <!-- <material name="dark"/> -->
    </visual>

    <!-- <collision>
      <origin xyz="0 0.0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04192569 0.03325003 0.02952809"/>
      </geometry>
    </collision> -->
  </link>


  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <!-- <xacro:sick_tim551 name="laser" ros_topic="scan" > -->

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0.09596655 0.0 0.1375" rpy="0 0 ${PI/2}"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/sensors/tim571.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <xacro:sensor_d435 parent="base_link" use_nominal_extrinsics="$(arg use_nominal_extrinsics)" add_plug="$(arg add_plug)" use_mesh="$(arg use_mesh)">
    <origin xyz="0.23495003 0.0 0.1490935" rpy="0 0 0"/>
  </xacro:sensor_d435>

  <!-- <joint name="camera_joint" type="fixed">
    <origin xyz="0.23495003 0.0 0.14990935" rpy="0 0 ${PI/2}"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
       <mesh filename="package://turtlebot3_description/meshes/sensors/d435.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision> -->

    <!-- This inertial field needs doesn't contain reliable data!! -->
  <!-- <inertial>
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
               iyy="0.000498940" iyz="0.0"
               izz="0.003879257" />
    </inertial>
  </link> -->

  <!-- <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/> -->

</robot>