#!/usr/bin/env python
#################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################

# Authors: Gilbert #

import rospy
import math
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
import time  # time module

LINEAR_VEL = 0.15
STOP_DISTANCE = 0.50
LIDAR_ERROR = 0.05
ANGLE = 90
SAFE_STOP_DISTANCE = STOP_DISTANCE + LIDAR_ERROR


class Obstacle():

    def __init__(self):
        self._cmd_pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
        self.obstacle()

    def get_scan(self):
        scan = rospy.wait_for_message('scan', LaserScan)
        scan_filter = []

        samples = len(scan.ranges)  # The number of samples is defined in
        # turtlebot3_<model>.gazebo.xacro file,
        # the default is 360.

        samples_view = ANGLE        # 1 <= samples_view <= samples

        if samples_view > samples:
            samples_view = samples

        if samples_view is 1:
            scan_filter.append(scan.ranges[0])

        else:
            left_lidar_samples_ranges = -(samples_view//2 + samples_view % 2)
            right_lidar_samples_ranges = samples_view//2

            left_lidar_samples = scan.ranges[left_lidar_samples_ranges:]
            right_lidar_samples = scan.ranges[:right_lidar_samples_ranges]
            scan_filter.extend(left_lidar_samples + right_lidar_samples)

        for i in range(samples_view):
            # set value to 3.5 in case of a faulty reading and hope we don't get all 0 readings
            if scan_filter[i] == float('Inf'):
                scan_filter[i] = 3.5
            elif math.isnan(scan_filter[i]):
                scan_filter[i] = 3.5
            elif scan_filter[i] == 0:
                scan_filter[i] = 3.5

        return scan_filter

    def obstacle(self):
        twist = Twist()
        turtlebot_moving = True
        t_end = time.time() + 60  # time_time returns time since 1st jan 1970
        speed_updates = 0  # for average speed
        speed_accumulation = 0  # for average speed
        collision_count = 0  # collision counter

        while time.time() < t_end:  # runs for 60 secs
            lidar_distances = self.get_scan()
            min_distance = min(lidar_distances)
            min_distance_right = min(lidar_distances[0:29])
            min_distance_center = min(lidar_distances[30:59])
            min_distance_left = min(lidar_distances[60:89])

            if min_distance_center < SAFE_STOP_DISTANCE:  # something need to be happen
                if min_distance_right < min_distance_left:
                    twist.linear.x = 0.05
                    twist.angular.z = 0.40  # left
                    self._cmd_pub.publish(twist)
                    rospy.loginfo('Turn left!')
                elif min_distance_left < min_distance_right:
                    twist.linear.x = 0.05
                    twist.angular.z = -0.40  # right
                    self._cmd_pub.publish(twist)
                    rospy.loginfo('Turn right!')
            else:
                twist.linear.x = LINEAR_VEL
                twist.angular.z = 0.0
                self._cmd_pub.publish(twist)
                turtlebot_moving = True
                rospy.loginfo('Distance of the obstacle : %f', min_distance)

            # collision
            if min_distance_center < 0.15 or min_distance_left < 0.15 or min_distance_right < 0.15:
                collision_count = collision_count + 1

            speed_updates = speed_updates + 1
            speed_accumulation = speed_accumulation + twist.linear.x

        rospy.loginfo('average speed : %f', speed_accumulation / speed_updates)
        rospy.loginfo('collision count : %f', collision_count)


def main():
    rospy.init_node('turtlebot3_obstacle')
    try:
        obstacle = Obstacle()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
